### ISSUE TITLE
Customizing scales

### ISSUE THREAD

**Issue by beattie** [drahnr/goatplot#14]
I'm writing a GUI for a USB oscilloscope.  For this I want to draw a grid(perhaps with dotted lines).  I don't want the scales with tick marks and numeric labels.  I would like to draw tick marks for the "zero position" of the traces, possibly in the same color of the trace, possibly with a small alpha numeric label.

It is possible to go down a rabbit hole designing a solution that is so flexible that it can do anything, but that way lies maddness.  I don't have a good notion of a way to do this that is flexible enough to do the scales I'd like and the scales that are appropriate for the more geberal uses of this package.  One thing that occurs to me, is to allow overiding the scale drawing function to allow completely arbitrary scales to be drawn.  I don't see this as replacing options for drawing scales but it could be usefull for cases that want greater control over the scales.

**Comment by drahnr** [comment]
I think this would require to make some kind of a GoatScaleRenderer interface and provide a default implementation.

Then make the constructor take arguments for each scale, use `NULL` as a special case where no scale is drawn.

This is totally doable and I already thought about that.

**Comment by drahnr** [comment]
#15 is a requirement for this.

Adding an overwritable render function is then pretty easy (and planned/in progress)

**Comment by drahnr** [comment]
Fixed with the merge of #15
