### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by m0nkeys** [drahnr/goatplot#23]
When compiling with any of the commands in the README, I get the following error messages:

[ 4/17] Compiling src/goat-scale-interface.c
In file included from ../../src/goat-scale-interface.c:1:0:
../../src/goat-scale-interface.h:10:58: error: expected ‘)’ before ‘GObject’
 G_DECLARE_INTERFACE (GoatScale, goat_scale, GOAT, SCALE, GObject)
                                                          ^
../../src/goat-scale-interface.h:31:25: error: unknown type name ‘GoatScale’
 void goat_scale_render (GoatScale *self);
                         ^
../../src/goat-scale-interface.h:36:23: error: unknown type name ‘GoatScale’
 void goat_scale_draw (GoatScale *self, cairo_t *cr, gint left, gint right, gint top, gint bottom, gdouble nil,
                       ^
../../src/goat-scale-interface.h:39:28: error: unknown type name ‘GoatScale’
 void goat_scale_get_range (GoatScale *scale, gdouble *min, gdouble *max);
                            ^
../../src/goat-scale-interface.h:40:33: error: unknown type name ‘GoatScale’
 void goat_scale_set_range_auto (GoatScale *scale);
                                 ^
../../src/goat-scale-interface.h:41:28: error: unknown type name ‘GoatScale’
 void goat_scale_set_range (GoatScale *scale, gdouble min, gdouble max);
                            ^
../../src/goat-scale-interface.h:42:31: error: unknown type name ‘GoatScale’
 void goat_scale_update_range (GoatScale *scale, gdouble min, gdouble max);
                               ^
../../src/goat-scale-interface.h:43:36: error: unknown type name ‘GoatScale’
 gboolean goat_scale_is_auto_range (GoatScale *scale);
                                    ^
../../src/goat-scale-interface.h:44:28: error: unknown type name ‘GoatScale’
 void goat_scale_grid_show (GoatScale *scale, gboolean show);
                            ^
In file included from /usr/include/glib-2.0/gobject/gobject.h:24:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/pi/goatplot/src/goat-plot-enum.h:4,
                 from ../../src/goat-scale-interface.h:4,
                 from ../../src/goat-scale-interface.c:1:
../../src/goat-scale-interface.c:3:21: error: unknown type name ‘GoatScaleInterface’
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
                     ^
/usr/include/glib-2.0/gobject/gtype.h:1718:50: note: in definition of macro ‘_G_DEFINE_INTERFACE_EXTENDED_BEGIN’
 static void     type_name##_default_init        (TypeName##Interface *klass); \
                                                  ^
/usr/include/glib-2.0/gobject/gtype.h:1495:47: note: in expansion of macro ‘G_DEFINE_INTERFACE_WITH_CODE’
 #define G_DEFINE_INTERFACE(TN, t_n, T_P)      G_DEFINE_INTERFACE_WITH_CODE(TN, t_n, T_P, ;)
                                               ^
../../src/goat-scale-interface.c:3:1: note: in expansion of macro ‘G_DEFINE_INTERFACE’
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
 ^
../../src/goat-scale-interface.c: In function ‘goat_scale_get_type’:
../../src/goat-scale-interface.c:3:21: error: ‘GoatScaleInterface’ undeclared (first use in this function)
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
                     ^
/usr/include/glib-2.0/gobject/gtype.h:1729:48: note: in definition of macro ‘_G_DEFINE_INTERFACE_EXTENDED_BEGIN’
                                        sizeof (TypeName##Interface), \
                                                ^
/usr/include/glib-2.0/gobject/gtype.h:1495:47: note: in expansion of macro ‘G_DEFINE_INTERFACE_WITH_CODE’
 #define G_DEFINE_INTERFACE(TN, t_n, T_P)      G_DEFINE_INTERFACE_WITH_CODE(TN, t_n, T_P, ;)
                                               ^
../../src/goat-scale-interface.c:3:1: note: in expansion of macro ‘G_DEFINE_INTERFACE’
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
 ^
../../src/goat-scale-interface.c:3:21: note: each undeclared identifier is reported only once for each function it appears in
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
                     ^
/usr/include/glib-2.0/gobject/gtype.h:1729:48: note: in definition of macro ‘_G_DEFINE_INTERFACE_EXTENDED_BEGIN’
                                        sizeof (TypeName##Interface), \
                                                ^
/usr/include/glib-2.0/gobject/gtype.h:1495:47: note: in expansion of macro ‘G_DEFINE_INTERFACE_WITH_CODE’
 #define G_DEFINE_INTERFACE(TN, t_n, T_P)      G_DEFINE_INTERFACE_WITH_CODE(TN, t_n, T_P, ;)
                                               ^
../../src/goat-scale-interface.c:3:1: note: in expansion of macro ‘G_DEFINE_INTERFACE’
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
 ^
../../src/goat-scale-interface.c:3:32: error: ‘goat_scale_default_init’ undeclared (first use in this function)
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
                                ^
/usr/include/glib-2.0/gobject/gtype.h:1730:56: note: in definition of macro ‘_G_DEFINE_INTERFACE_EXTENDED_BEGIN’
                                        (GClassInitFunc)type_name##_default_init, \
                                                        ^
/usr/include/glib-2.0/gobject/gtype.h:1495:47: note: in expansion of macro ‘G_DEFINE_INTERFACE_WITH_CODE’
 #define G_DEFINE_INTERFACE(TN, t_n, T_P)      G_DEFINE_INTERFACE_WITH_CODE(TN, t_n, T_P, ;)
                                               ^
../../src/goat-scale-interface.c:3:1: note: in expansion of macro ‘G_DEFINE_INTERFACE’
 G_DEFINE_INTERFACE (GoatScale, goat_scale, G_TYPE_OBJECT);
 ^
../../src/goat-scale-interface.c: At top level:
../../src/goat-scale-interface.c:5:38: error: unknown type name ‘GoatScaleInterface’
 static void goat_scale_default_init (GoatScaleInterface *iface)
                                      ^
../../src/goat-scale-interface.c:15:23: error: unknown type name ‘GoatScale’
 void goat_scale_draw (GoatScale *self, cairo_t *cr, gint left, gint right, gint top, gint bottom, gdouble nil,
                       ^
../../src/goat-scale-interface.c:28:25: error: unknown type name ‘GoatScale’
 void goat_scale_render (GoatScale *self)
                         ^
../../src/goat-scale-interface.c:38:28: error: unknown type name ‘GoatScale’
 void goat_scale_get_range (GoatScale *self, gdouble *min, gdouble *max)
                            ^
../../src/goat-scale-interface.c:48:33: error: unknown type name ‘GoatScale’
 void goat_scale_set_range_auto (GoatScale *self)
                                 ^
../../src/goat-scale-interface.c:58:28: error: unknown type name ‘GoatScale’
 void goat_scale_set_range (GoatScale *self, gdouble min, gdouble max)
                            ^
../../src/goat-scale-interface.c:68:31: error: unknown type name ‘GoatScale’
 void goat_scale_update_range (GoatScale *self, gdouble min, gdouble max)
                               ^
../../src/goat-scale-interface.c:78:36: error: unknown type name ‘GoatScale’
 gboolean goat_scale_is_auto_range (GoatScale *self)
                                    ^
../../src/goat-scale-interface.c:89:28: error: unknown type name ‘GoatScale’
 void goat_scale_grid_show (GoatScale *self, gboolean show)
                            ^

In file included from ../../src/goat-plot.h:26:0,
                 from ../../src/goat-plot.c:21:
../../src/goat-scale-interface.h:10:58: error: expected ‘)’ before ‘GObject’
 G_DECLARE_INTERFACE (GoatScale, goat_scale, GOAT, SCALE, GObject)
                                                          ^
../../src/goat-scale-interface.h:31:25: error: unknown type name ‘GoatScale’
 void goat_scale_render (GoatScale *self);
                         ^
../../src/goat-scale-interface.h:36:23: error: unknown type name ‘GoatScale’
 void goat_scale_draw (GoatScale *self, cairo_t *cr, gint left, gint right, gint top, gint bottom, gdouble nil,
                       ^
../../src/goat-scale-interface.h:39:28: error: unknown type name ‘GoatScale’
 void goat_scale_get_range (GoatScale *scale, gdouble *min, gdouble *max);
                            ^
../../src/goat-scale-interface.h:40:33: error: unknown type name ‘GoatScale’
 void goat_scale_set_range_auto (GoatScale *scale);
                                 ^
../../src/goat-scale-interface.h:41:28: error: unknown type name ‘GoatScale’
 void goat_scale_set_range (GoatScale *scale, gdouble min, gdouble max);
                            ^
../../src/goat-scale-interface.h:42:31: error: unknown type name ‘GoatScale’
 void goat_scale_update_range (GoatScale *scale, gdouble min, gdouble max);
                               ^
../../src/goat-scale-interface.h:43:36: error: unknown type name ‘GoatScale’
 gboolean goat_scale_is_auto_range (GoatScale *scale);
                                    ^
../../src/goat-scale-interface.h:44:28: error: unknown type name ‘GoatScale’
 void goat_scale_grid_show (GoatScale *scale, gboolean show);
                            ^
In file included from ../../src/goat-plot.c:21:0:
../../src/goat-plot.h:57:26: error: unknown type name ‘GoatScale’
 GoatPlot *goat_plot_new (GoatScale *scale_x, GoatScale *scale_y);
                          ^
../../src/goat-plot.h:57:46: error: unknown type name ‘GoatScale’
 GoatPlot *goat_plot_new (GoatScale *scale_x, GoatScale *scale_y);
                                              ^
../../src/goat-plot.h:66:45: error: unknown type name ‘GoatScale’
 void goat_plot_set_scale_x (GoatPlot *plot, GoatScale *scale_x);
                                             ^
../../src/goat-plot.h:67:45: error: unknown type name ‘GoatScale’
 void goat_plot_set_scale_y (GoatPlot *plot, GoatScale *scale_y);
                                             ^
../../src/goat-plot.c:41:2: error: unknown type name ‘GoatScale’
  GoatScale *scale_x;
  ^
../../src/goat-plot.c:42:2: error: unknown type name ‘GoatScale’
  GoatScale *scale_y;
  ^
In file included from ../../src/goat-plot.c:47:0:
../../src/goat-plot-internal.h: In function ‘draw_scales’:
../../src/goat-plot-internal.h:37:2: warning: implicit declaration of function ‘GOAT_IS_SCALE’ [-Wimplicit-function-declaration]
  g_assert (GOAT_IS_SCALE (priv->scale_x));
  ^
../../src/goat-plot-internal.h:45:2: warning: implicit declaration of function ‘goat_scale_draw’ [-Wimplicit-function-declaration]
  goat_scale_draw (priv->scale_x, cr, left, right, top, bottom, x_nil, x_unit_to_pixel);
  ^
../../src/goat-plot.c: At top level:
../../src/goat-plot.c:165:26: error: unknown type name ‘GoatScale’
 GoatPlot *goat_plot_new (GoatScale *x, GoatScale *y)
                          ^
../../src/goat-plot.c:165:40: error: unknown type name ‘GoatScale’
 GoatPlot *goat_plot_new (GoatScale *x, GoatScale *y)
                                        ^
../../src/goat-plot.c:173:45: error: unknown type name ‘GoatScale’
 void goat_plot_set_scale_x (GoatPlot *plot, GoatScale *scale)
                                             ^
../../src/goat-plot.c:181:45: error: unknown type name ‘GoatScale’
 void goat_plot_set_scale_y (GoatPlot *plot, GoatScale *scale)
                                             ^
../../src/goat-plot.c: In function ‘draw’:
../../src/goat-plot.c:376:3: warning: implicit declaration of function ‘goat_scale_is_auto_range’ [-Wimplicit-function-declaration]
   const gboolean register autorange_x = goat_scale_is_auto_range (priv->scale_x);
   ^
../../src/goat-plot.c:379:4: warning: implicit declaration of function ‘goat_scale_get_range’ [-Wimplicit-function-declaration]
    goat_scale_get_range (priv->scale_x, &ref_x_min, &ref_x_max);
    ^
../../src/goat-plot.c:404:4: warning: implicit declaration of function ‘goat_scale_update_range’ [-Wimplicit-function-declaration]
    goat_scale_update_range (priv->scale_x, ref_x_min, ref_x_max);
    ^
../../src/goat-plot.c: At top level:
../../src/goat-plot.c:501:17: warning: ‘event’ defined but not used [-Wunused-function]
 static gboolean event (GtkWidget *widget, GdkEvent *event)
                 ^

Waf: Leaving directory `/home/pi/goatplot/build/debug'
Build failed
 -> task in 'objects' failed (exit status 1):
        {task 1968112144: c goat-scale-interface.c -> goat-scale-interface.c.1.o}
['/usr/bin/gcc', '-ggdb', '-Wall', '-fPIC', '-pthread', '-pthread', '-I/home/pi/goatplot/build/debug/src', '-I/home/pi/goatplot/src', '-I/usr/include/glib-2.0', '-I/usr/lib/arm-linux-gnueabihf/glib-2.0/include', '-I/usr/include/gtk-3.0', '-I/usr/include/at-spi2-atk/2.0', '-I/usr/include/at-spi-2.0', '-I/usr/include/dbus-1.0', '-I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/harfbuzz', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-D_FILE_OFFSET_BITS=64', '-DVERSION="0.0.11"', '-DGETTEXT_PACKAGE="goatplot"', '-DHAVE_LARGEFILE=1', '-DINLINE_MACRO=1', '-DDEBUG=1', '-DHAVE_GOBJECT=1', '-DHAVE_GLIB=1', '-DHAVE_GTK3=1', '../../src/goat-scale-interface.c', '-c', '-o', '/home/pi/goatplot/build/debug/src/goat-scale-interface.c.1.o']
 -> task in 'objects' failed (exit status 1):
        {task 1968112080: c goat-plot.c -> goat-plot.c.1.o}
['/usr/bin/gcc', '-ggdb', '-Wall', '-fPIC', '-pthread', '-pthread', '-I/home/pi/goatplot/build/debug/src', '-I/home/pi/goatplot/src', '-I/usr/include/glib-2.0', '-I/usr/lib/arm-linux-gnueabihf/glib-2.0/include', '-I/usr/include/gtk-3.0', '-I/usr/include/at-spi2-atk/2.0', '-I/usr/include/at-spi-2.0', '-I/usr/include/dbus-1.0', '-I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include', '-I/usr/include/gio-unix-2.0', '-I/usr/include/cairo', '-I/usr/include/pango-1.0', '-I/usr/include/harfbuzz', '-I/usr/include/atk-1.0', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-I/usr/include/gdk-pixbuf-2.0', '-D_FILE_OFFSET_BITS=64', '-DVERSION="0.0.11"', '-DGETTEXT_PACKAGE="goatplot"', '-DHAVE_LARGEFILE=1', '-DINLINE_MACRO=1', '-DDEBUG=1', '-DHAVE_GOBJECT=1', '-DHAVE_GLIB=1', '-DHAVE_GTK3=1', '../../src/goat-plot.c', '-c', '-o', '/home/pi/goatplot/build/debug/src/goat-plot.c.1.o']

**Comment by m0nkeys** [comment]
This is the output of ./waf configure:

Setting top to                           : /home/pi/goatplot
Setting out to                           : /home/pi/goatplot/build
Checking for 'gcc' (C compiler)          : /usr/bin/gcc
Checking for program 'glib-genmarshal'   : /usr/bin/glib-genmarshal
Checking for program 'perl'              : /usr/bin/perl
Checking for program 'glib-mkenums'      : /usr/bin/glib-mkenums
Checking for program 'glib-compile-schemas' : /usr/bin/glib-compile-schemas
Checking for program 'glib-compile-resources' : /usr/bin/glib-compile-resources
Checking for library m                        : yes
Checking for program 'pkg-config'             : /usr/bin/pkg-config
Checking for pkg-config version >= '0.26'     : yes
Checking for 'glib-2.0'                       : yes
Checking for 'gobject-2.0'                    : yes
Checking for 'gtk+-3.0'                       : yes
Checking for large file support               : no
Checking for -D_FILE_OFFSET_BITS=64           : yes
Checking for endianness                       : little
Checking for inline                           : inline
Checking for library m                        : yes
Checking for pkg-config version >= '0.26'     : yes
Checking for 'glib-2.0'                       : yes
Checking for 'gobject-2.0'                    : yes
Checking for 'gtk+-3.0'                       : yes
Checking for large file support               : yes
Checking for endianness                       : little
Checking for inline                           : inline

**Comment by drahnr** [comment]
Can you please add the output of the following files:

`cat /etc/*-release `
`cat /proc/version`
`pkg-config --libs --cflags gtk+-3.0`

From your project directory:
`git log -n1`

Please also properly highlight code or shell output properly, the logs you posted are hardly readable.

---

I just verified that latest git builds just fine on my laptop.

**Comment by m0nkeys** [comment]
Thanks for looking into this. Here is the output:

**> cat /etc/*-release**
        PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="8"
    VERSION="8 (jessie)"
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**>cat /proc/version**
    Linux version 4.4.13-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #894 SMP Mon Jun 13 13:13:27 BST 2016

**>pkg-config --libs --cflags gtk+-3.0**
-pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0

**>git log -n1**
commit c96b93fa65c96e5698c3618694bb7693540e8e23
Author: Bernhard Schuster <bernhard@ahoi.io>
Date:   Fri Jul 29 08:41:36 2016 +0200

    Move from `*_GET_PRIVATE` macros to `*_get_instance_private` functions

    Those are autodeclared `G_DEFINE_TYPE_WITH_PRIVATE` anyways, requires `glib` >= 2.38 which was released 2013-09-23.

**Comment by drahnr** [comment]
Ok, your checkout is up-to-date.

My guess would be that your glib version is too old, since this particular commit did raise the requirements to `glib >= 2.38` and my guess would be that raspbian does not satisfy this requirement (read: that version is from 2013 if I remember correctly).


Can you check:

`pkg-config --modversion glib-2.0`

For me on Fedora 24 this is `2.48.2`.

**Comment by m0nkeys** [comment]
I've got version 2.42.1, so this should satisfy the requirements. But I'll try to compile the latest version.

**Comment by drahnr** [comment]
Please report back how it goes, this is a bit of a strange issue and I'd like to know the reason behind it.

Also try to wipe anything stale 'git reset --hard HEAD && git clean -dfx && ./waf distclean && ./waf configure && ./waf'

**Comment by m0nkeys** [comment]
It works with the latest version 2.48.2 of glib, which I compiled from source. Thanks for your help!

**Comment by drahnr** [comment]
Closing, see #24
