### ISSUE TITLE
Build failure message

### ISSUE THREAD

**Issue by beattie** [drahnr/goatplot#6]
When I run "./waf build --no-glade-dtd-check" the library builds and the tests seem to complete correctly, but I get the following:
beattie@kokopelli:~/git/goatplot$ ./waf build --no-glade-dtd-check
Waf: Entering directory `/home/beattie/git/goatplot/build'
Variant: ''
[11/14] Processing build/test-screenshot
[14/14] Processing build/test-dynamic
Running test 'test-screenshot'           : passed 
Waf: Leaving directory `/home/beattie/git/goatplot/build'
Build failed
Traceback (most recent call last):
  File "/home/beattie/git/goatplot/.waf-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Task.py", line 110, in process
    ret=self.run()
  File ".wafcustom/unites.py", line 146, in run
    raise Errors.WafError('Test \'%s\' failed' % (testname))
WafError: Test 'test-screenshot' failed

**Comment by drahnr** [comment]
If you add `--notests` none of the tests will be executed. This is what you should do for debian package builds.

**Comment by drahnr** [comment]
Also: Does this happen with or without your PR changes applied?

**Comment by beattie** [comment]
To answer your question I reverted my local repository to before my commits and I get the error.  However; If I re-clone my github repository I don't get the error, with or with out the commits.  I'd guess I messed up the configure but not knowing waf I don't know where to look,  I did a "./waf distclean" but the same error.  I looked at the Waf Book and it looks pretty involved.

**Comment by beattie** [comment]
So, the error is back.  If I remove the repository and clone either my fork or yours I get the message.  Something is screwed up in my python or waf configuration.  I have no idea, the test runs fine, it just reports an error.

**Comment by drahnr** [comment]
I was not able to reproduce this.

**Comment by beattie** [comment]
Seems to have been fixed by your last commit.  Will watch for a while.
